### ISSUE TITLE
Make prior MySQL/MariaDB Based wallets be able to Upgrade to the current Schema

### ISSUE THREAD

**Issue by ac0v** [PoC-Consortium/burstcoin#109]

**Comment by 4nt1g0** [comment]
I just verified that upgrading 1.3.6cg to 1.9.1 works fine. Did you have anything concrete in mind that is still to do?

**Comment by Quibus-burst** [comment]
For me it did not work. What is your Maria version ?

**Comment by 4nt1g0** [comment]
it's 10.0.10-MariaDB. What was the problem on your side?

For me the only differences between 1.3.6cg schema and 1.9.1 schema were
1. account: column creation_HEIGHT -> creation_height
2. goods: column ID -> id
3. peer: column address now has collation utf8mb4_unicode_ci
4. purchase_public_feedback: column public_feedback now has collation utf8mb4_unicode_ci
5. transaction: column referenced_transaction_full_hash -> referenced_transaction_fullhash

1, 2 and 5 are already taken care of in `MariadbDbVersion.java`, 3 is irrelevant because ipv6 addresses do not use emojis afaik and the table for 4 is empty.

**Comment by Quibus-burst** [comment]
it was #5 that hanged for me. But i upgraded the MariaDB version and all is working fine after that.. tried multiple times.

**Comment by ac0v** [comment]
just rechecked on different test servers. works perfectly. thanks for testing :-)
