### ISSUE TITLE
Towards a v2 API

### ISSUE THREAD

**Issue by rico666** [PoC-Consortium/burstcoin#125]
Design and implement a /v2/  API which is sound (answer performance, efficient queries), extensible and comprehensive.

We will keep the old v1 API for as long as necessary, but hopefully v2 will allow us to phase it out eventually.

**Comment by rico666** [comment]
`getUnconfirmedTransactions` improvement:

Give an incoming unconfirmed transaction an "arrivalTime" timestamp. The time when it has been made aware to the node. Then, a query

    {
      "protocol":"B1",
      "requestType":"getUnconfirmedTransactions",
      "tresholdTime": xxxx
    }

could get only those that arrived new/changed since the last query. At the moment all unconfirmed transactions in a nodes memory are sent upon this request - currently every 5 seconds.

**Comment by rico666** [comment]
@ac0v Layer suggestion: use gRPC (https://grpc.io/) as transport layer instead of our HTTP/1.1 JSON data diddling.

Pros:
* Much more efficient

Cons:
* inherently not human-readable
* Must make sure we have good debugging/introspection capabilities. 
* (probably) - we have also HTTP/2 capability in Jetty 9.4 question is why we don't make use of that and introduce something 3rd

We will not be able to use gRPC for regular API (or will we? - Not without completely rewriting the code). So maybe try HTTP/2 + JSON first? Baby steps...

**Comment by rico666** [comment]
Remove protocol boilerplate `protocol: B1` from each request. All nodes will have to upgrade anyway. Make a 2.0.X release that does not require it anymore - its not used for any distinction, there are no different protocols in use concurrently.

There should definitely be a version "of the protocol used", but this could be queried in the `getInfo`.

**Comment by bradfordcp** [comment]
It would be nice to see meaningful routes `/api/v2/accounts/:account_id/subscriptions` vs url parameters `requestType=getAccountSubscriptions`. It may be worth aligning around common controllers similar to the MVC pattern.

Additionally HTTP status codes could help impart the status of a request. Right now it seems as though everything is a `200 OK` status code vs `404 Not Found` or `400 Bad Request`.

**Comment by Brabantian** [comment]
@bradfordcp I agree that it could be a good idea to move to a RESTful interface, for the HTTP layer (communication towards wallet front-end, and other applications).

When it comes to the Peers interface (wallet to wallet) it will depend on the technology that is used. The current HTTP vs GRPC vs avian carriers or whatever. Because that's only for wallet to wallet communication though, it's far less of a gain there anyhow.

Grouping into controllers is definitely not a bad idea either, it could potentially cut down in the LoC of the current HTTP layer. We'll need to do some technical experimentation and refactoring in how we'd want to structure that, though, since it would mean we'd have to step off of our current APIRequestHandler interface.
